version: "3"

services:
  db-dev:
    image: mysql:8.0.29
    environment:
      MYSQL_DATABASE: db_dev
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    container_name: tomeit-api-db-dev
    restart: always
    volumes:
      - data-dev:/var/lib/mysql
  db-test:
    image: mysql:8.0.29
    environment:
      MYSQL_DATABASE: db_test
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    container_name: tomeit-api-db-test
    restart: always
    ports:
      - "13306:3306"
    volumes:
      - data-test:/var/lib/mysql

volumes:
  data-dev:
    driver: local
  data-test:
    driver: local
